### ISSUE TITLE
getAdapterPosition not resolving when first created

### ISSUE THREAD

**Issue by peavers** [kanytu/Android-studio-material-template#10]
Line 43 and 47 of NavigationDrawerAdapter can't seem to resolve getAdapterPosition even after confirming a successful gradle build and the right support imports. Changing to the depreciated getPosition method lets the project build and work as expected.

**Comment by kanytu** [comment]
Could you tell me what's the latest build tools you have installed? Show me the build.gradle from your app module please.

**Comment by peavers** [comment]
Running the latest version of android studio, created a fresh project with a minimum API 21 and everything as default. 

 buildToolsVersion "21.1.2"

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "org.example.myapplication"
        minSdkVersion 21
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:support-v4:21.0.3'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.android.support:recyclerview-v7:21.0.3'
}
```

**Comment by kanytu** [comment]
You're right. `getAdapterPosition` was added on support library v22:

http://developer.android.com/tools/support-library/index.html#rev21

So if you don't have it installed it will not be successfully resolved.
I will have to add an if condition to check the current installed library and change the method accordingly.

Thanks for pointing that out

**Comment by kanytu** [comment]
I think it's fixed now:

https://github.com/kanytu/Android-studio-material-template/archive/master.zip

If you could give it a try it would be great. If it still doesn't work reopen the issue :)

Have a nice day

**Comment by peavers** [comment]
Defaulted to getPosition as expected.

Cheers for a great plugin!
