### ISSUE TITLE
How can i have back button on specific fragment ?

### ISSUE THREAD

**Issue by Vivalemuc** [kanytu/Android-studio-material-template#12]
I would like to display back button (instead of menu button) on specific fragment ? And when i click on, i go back on previous fragment.

It is possible ?

**Comment by kanytu** [comment]
Yes it is possible. Just add a button on your fragment's layout file and add a click listener to it. Next, on `onClick` you can call `getActivity().onBackPressed();`.

Hope it helps

**Comment by Vivalemuc** [comment]
I want replace the menu button on the toolbar by a back button ? It is possible !

Sorry for my english, i am french ^^

**Comment by kanytu** [comment]
To show the "back" arrow just use this method:

```
/**
 * Changes the icon of the drawer to back
 */
public void showBackButton() {
    if (getActivity() instanceof ActionBarActivity) {
        ((ActionBarActivity) getActivity()).getSupportActionBar().setDisplayHomeAsUpEnabled(true);
    }
}
```

To show back the drawer icon just use this method: 

```
/**
 * Changes the icon of the drawer to menu
 */
public void showDrawerButton() {
    if (getActivity() instanceof ActionBarActivity) {
        ((ActionBarActivity) getActivity()).getSupportActionBar().setDisplayHomeAsUpEnabled(false);
    }
    mActionBarDrawerToggle.syncState();
}
```

**Comment by Vivalemuc** [comment]
Thanks you ! 

And how handle the click on this button ? To decide on a specific fragment to do "back pressed" instead of "show menu" ?

**Comment by kanytu** [comment]
On your activity's `onBackPressed` method you can change it to this:

```
@Override
public void onBackPressed() {
    if (mNavigationDrawerFragment.isDrawerOpen())
        mNavigationDrawerFragment.closeDrawer();
    else if (getFragmentManager().getBackStackEntryCount()>0)
        getFragmentManager().popBackStack();
    else
        super.onBackPressed();
}
```

What this change will do is: It will check the backstack count of your FragmentManager and if there are fragments on it, it will pop the fragment. So for this to work make sure you call `.addToBackStack()` on your fragment transaction as well.

**Comment by Vivalemuc** [comment]
It's perfect !

Thanks you very much for your library, it's amazing !

**Comment by Vivalemuc** [comment]
The arrow drawable works perfectly ;)

But when i click on it, the drawer is diplayed. I want the onBackPressed !

**Comment by kanytu** [comment]
I will check this later but could you read this answer I posted on stackoverflow? http://stackoverflow.com/a/26671641/3410697

**Comment by kanytu** [comment]
@Vivalemuc  Is the problem solved?

**Comment by Vivalemuc** [comment]
I will try later, for now consider yes !

Thanks you !

**Comment by gajendrakumartwinwal** [comment]
Getting same issue mentioned by @Vivalemuc 
The arrow drawable works perfectly ;)

But when i click on it, the drawer is diplayed. I want the onBackPressed !

**Comment by mmaksitaliev** [comment]
@Vivalemuc  @gajendrakumartwinwal I haven't tested, but I think this should work: 

```
@Override
public void onBackPressed() {
    if (mNavigationDrawerFragment.isDrawerOpen())
        mNavigationDrawerFragment.closeDrawer();
    else if (getFragmentManager().getBackStackEntryCount()>0 && !mNavigationDrawerFragment.isDrawerOpen())
        getFragmentManager().popBackStack();
    else
        super.onBackPressed();
}
```
