### ISSUE TITLE
Replace deprecated ActionBarActivity with AppCompatActivity

### ISSUE THREAD

**Issue by ghost** [kanytu/Android-studio-material-template#17]
When creating an application from this template, the main activity is declared thus:

public class MainActivity extends ActionBarActivity

ActionBarActivity is deprecated and could be replaced with its replacement AppCompatActivity:

public class MainActivity extends AppCompatActivity

This is in file MaterialNavigationDrawerActivity\root\src\app_package\DrawerActivity.java.ftl, lines 6 & 15:

```
import android.support.v7.app.ActionBarActivity;
```

and

```
public class ${activityClass} extends ActionBarActivity
```

to 

```
import android.support.v7.app.AppCompatActivity;
```

and

```
public class ${activityClass} extends AppCompatActivity
```

**Comment by kanytu** [comment]
Can't be done:

https://github.com/kanytu/Android-studio-material-template/pull/13
