### ISSUE TITLE
Problems with Android Studio 1.2.0 update

### ISSUE THREAD

**Issue by joen93** [kanytu/Android-studio-material-template#18]
I tried to update to 1.2.0 today and I ran into this problem.
![screenshot from 2015-05-05 09 14 22](https://cloud.githubusercontent.com/assets/3929077/7468324/53878d5c-f307-11e4-9b41-0e2426cd695f.png)

I'm guessing that I should just update to 1.2.0 and afterwards insert the template manually again?

**Comment by kevindesai777** [comment]
Yes. After every Android studio update, the template gets removed. So just put it again.

**Comment by kanytu** [comment]
This is true. The template gets erased as well as any customization on android studio (vm options etc). 

To avoid having to install the template you can put it on the SDK folder. Check this issue for better understanding of this solution:

https://github.com/kanytu/Android-studio-material-template/issues/14
