### ISSUE TITLE
Main Activity Overlaps Fragements

### ISSUE THREAD

**Issue by adhikjoshi** [kanytu/Android-studio-material-template#20]
Your Template is awesome,
there is issue that when i open other activity from navigation drawer then it overlaps main activity...
i have uploaded screenshots need help....

i have uploaded my project in zip file.
link is 
https://drive.google.com/file/d/0BykGyq2bS2o9cmhsRndMOFVnZjA/view?usp=sharing

help me...

![device-2015-05-07-095227](https://cloud.githubusercontent.com/assets/11740719/7508620/f830c496-f4a0-11e4-8f41-007b76f369c1.png)
![device-2015-05-07-095253](https://cloud.githubusercontent.com/assets/11740719/7508621/f8b43c18-f4a0-11e4-9b51-47031fc2e11e.png)
![device-2015-05-07-100601](https://cloud.githubusercontent.com/assets/11740719/7508622/f8f5250c-f4a0-11e4-895e-a1382bd59884.png)

**Comment by kanytu** [comment]
that has nothing to do with the template itself.

you're probably using a transparent theme for your activity. Either change it or set the background of your activity to white (tho that will create overdraw)
