### ISSUE TITLE
Duplicate menu items

### ISSUE THREAD

**Issue by alexpahomi** [kanytu/Android-studio-material-template#28]
Olá Pedro! 
When there are more options added to menu so they are scrollable, the menu items are duplicated, one set stay in place, another is scrollable. I used the following flow:
1. Open the app
2. Open the menu and scroll it -> everything should be fine
3. Click on one of the options so the fragment is changed
4. Open the menu again and scroll it -> options are duplicated.

Bellow is a link to a video to be more explicit http://apollo.eed.usv.ro/~pahomi_a/for_pedro_o.html.
The appears on LG G3, Nexus 4, both running Android L. Works fine on Samsung Galaxy S4, S5(Android L for both), Samsung Note - N7000, Note 2, Samsung A3, A5.

**Comment by kanytu** [comment]
It looks like there are multiple instances of the navigation drawer in one place. Are you sure you're not creating another menu when you open an item from it?

**Comment by alexpahomi** [comment]
I tfound the problem. The other dev changed the code in Adapter and set the items to be not recycleable in onBindViewHolder (viewHolder.setIsRecyclable(false); ). Thank you for pointing me to the right direction.

**Comment by kanytu** [comment]
No problem :)
