### ISSUE TITLE
Drawer layout scrolls behind image view

### ISSUE THREAD

**Issue by martipello** [kanytu/Android-studio-material-template#29]
The gmail style layout from template  scrolls behind or underneath the image header how could I put one in the other so the header scrolls away when scrolled up?
Also..
Calls first fragment when rotated but I'll fix this

**Comment by kanytu** [comment]
I'm afraid I don't understand the issue. Could you explain it with examples?

**Comment by martipello** [comment]
Sorry, to elaborate when you scroll the drawer up i expect it to scroll like the gmail app where the image header scrolls away behind the toolbar like its attached to the recycler view, yours scrolls below the header like they are not attached

**Comment by kanytu** [comment]
You need to check the the correct drawer style:

http://i.imgur.com/qS2nJ7T.png

**Comment by martipello** [comment]
I chose the gmail styled one, wish I could send you some screenshots
