### ISSUE TITLE
Get "getSupportActionbar setTitle" to work

### ISSUE THREAD

**Issue by martipello** [kanytu/Android-studio-material-template#31]
hi sorry to bother you im trying to change the title on each fragment without any success, ive tried changing it from main activity inside onNavigationDrawerItemSelected by using ActionBarActivity.getSupportActionBar.setTitle(onNavigationDrawerItemSelected(position)) this gives me an error that it cannot be referenced from a static context removing the ActionBarActivity call tells me it cannot resolve setTitle.
and ive tried changing it from the fragment by including the toolbar and changing the title like this 
setTitle("My Title");
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar_actionbar);
        setSupportActionBar(toolbar);
but again no success can you give me some help please?

**Comment by kanytu** [comment]
The kind of questions you're asking here have nothing to do with the template itself. They are not bugs or issues whatsoever. This is not a place for such questions. Imagine every one would post an issue every time they don't know how to achieve something. 

Consider using StackOverflow for such questions.
Good luck

**Comment by martipello** [comment]
Yeah I know its just I saw on your blog someone who was stuck and you asked
them to raise an issue on github for additional help, sorry to post in the
wrong place, thanks for replying
