### ISSUE TITLE
Compatibility Issues 

### ISSUE THREAD

**Issue by ghost** [kanytu/Android-studio-material-template#32]
I just thought to post this here if anyone is interested to update the template: 
1) The `ActionBarActivity` is depreciated in 22.1.0, so line 15 of [DrawerActivity](https://github.com/kanytu/Android-studio-material-template/blob/50ffab372b5b8b9e05928caddabfaa5dfbb06b1a/MaterialNavigationDrawerActivity/root/src/app_package/DrawerActivity.java.ftl#L15) : 
`public class ${activityClass} extends ActionBarActivity`
should be updated with `AppCompatActivity`. 

2) in `ScrimInsetsFrameLayout` the getSystemWindowInsetBottom call requires api 20, an if statement to check the built would be better. something like this : 
`if (Build.VERSION.SDK_INT >= 20) {....}`

3) `fitSystemWindows` is depreciated 

Update: I just saw this topic [https://github.com/kanytu/Android-studio-material-template/issues/17](https://github.com/kanytu/Android-studio-material-template/issues/17) regarding first issue. @kanytu what do you mean it can't be done? I just replaced it with AppCompatActivity, did a clean build and everything worked fine.

**Comment by martipello** [comment]
To add to that for the same effect in KitKat you can have a translucent
status bar theme for styles-v19, and for  v19, v21 dimens you can set
margin top to 24dp for v19 and 0dp for v21

**Comment by kanytu** [comment]
1) No it shouldn't. Otherwise it will not compile for developers which haven't updated their APIs yet.

2) No need because "dispatchApplyWindowInsets" is only called in api level20...

3) And it's there for compatibility purposes.... dispatchApplyWindowInsets for >=20 fitSystemWindows for <20
