### ISSUE TITLE
can't select item

### ISSUE THREAD

**Issue by thib3113** [kanytu/Android-studio-material-template#5]
i have a problem, when i click on a item, sometimes, i can't select.

The text change color on hover, but item don't change.

Better one long explain, i have make a repo : https://github.com/thib3113/EVA-Android
the bug is not very visible with emulator, but i can see this on my nexus 5 5.1
thank you for help

**Comment by thib3113** [comment]
it's ok, i reset my project and it's work

**Comment by Jonathan727** [comment]
This sounds similar to my issue, [Unresponsive Navigation Buttons](https://github.com/kanytu/android-material-drawer-template/issues/43)
