### ISSUE TITLE
how to hide drawer or lock on one item

### ISSUE THREAD

**Issue by thib3113** [kanytu/Android-studio-material-template#6]
what need I to do, if for example i need to hide the drawer, or lock on one item ?

**Comment by kanytu** [comment]
This is not a forum to ask for questions nor this is an issue with the library itself. Keep in mind that questions like this should be posted a forum for the effect. I would suggest stackoverflow.com for that.

**Comment by thib3113** [comment]
yes i know, and i search in stackoverflow, who i found : 

``` java
View frag = findViewById(R.id.my_fragment);
frag.setVisibility(View.INVISIBLE);
```

but it's don't work with your library .

So, i think you library have a custom function for do that, but it's ok, i need search other things

**Comment by kanytu** [comment]
What do you want to do? Close the drawer? The drawer (or menu) can be closed by calling `closeDrawer`.

**Comment by thib3113** [comment]
I wanted to lock on one item ( the user can change if i don't unlock ), or hide the drawer ( close immediately ), so I have hide the parent, and it's ok
