### ISSUE TITLE
 Wrong line separators again but line 635

### ISSUE THREAD

**Issue by trungkiendang** [kanytu/Android-studio-material-template#7]
I'm using Android studio with mac os x, when i try to add Template it say: 
 Wrong line separators: '...e License.\r\n-->\n\n\n\n<re...' at offset 635 (show balloon)

please help!

**Comment by kanytu** [comment]
Check the other issues for help

**Comment by trungkiendang** [comment]
#1 can't sloved problem for me. plz check it again...

**Comment by kanytu** [comment]
Could you describe how are you installing the template?

**Comment by trungkiendang** [comment]
I clone lastest version of git and download release   in you blog. But both can't creat template.

**Comment by trungkiendang** [comment]
I followed all step to setup template

**Comment by kanytu** [comment]
I'm not on my PC right now. And I find really weird that bug. Could you search for a tool called dos2unix and run that tool on the file that is generating the problem. Or build a script that runs that tool on all files?

**Comment by trungkiendang** [comment]
I'm sorry, i try to use dos2unix to replace \r\n --> \n\n but it not work, same error. :D
I'm comeback to win to create project to use template. but you fix it next version. Thank a lot!

**Comment by kanytu** [comment]
I've been looking at my project and I don't seem to find any word "License" on it. Could you tell me what file is creating the error?
